onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpu_tb_rf/I2C_error_out
add wave -noupdate /cpu_tb_rf/reset_n
add wave -noupdate /cpu_tb_rf/sys_clock
add wave -noupdate /cpu_tb_rf/digital_in
add wave -noupdate /cpu_tb_rf/digital_out
add wave -noupdate /cpu_tb_rf/I2C_sda
add wave -noupdate /cpu_tb_rf/I2C_scl
add wave -noupdate /cpu_tb_rf/CPU_top/digital_in
add wave -noupdate /cpu_tb_rf/CPU_top/digital_out
add wave -noupdate /cpu_tb_rf/CPU_top/I2C_sda
add wave -noupdate /cpu_tb_rf/CPU_top/I2C_scl
add wave -noupdate /cpu_tb_rf/CPU_top/I2C_error_out
add wave -noupdate /cpu_tb_rf/CPU_top/PC_top_level
add wave -noupdate -expand /cpu_tb_rf/CPU_top/control_unit_top/LAB/branches
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/condition_met
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/condition_met
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/results_available
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/zero_inst_match
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/clear_zero_inst
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/speculate_results
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/frst_branch_index
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/scnd_branch_index
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/PC
add wave -noupdate /cpu_tb_rf/CPU_top/PM_data
add wave -noupdate /cpu_tb_rf/CPU_top/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_reset_out
add wave -noupdate -expand /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/ROB_actual
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/jump
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/PM_datahaz_status
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/PL_datahaz_status
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/LAB_datahaz_status
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/branch
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/branch_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/bne
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/bnez
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/condition_met
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/results_available
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/branch_exists
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/is_unresolved
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/bne_from_ROB
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/bnez_from_ROB
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/LAB_full
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/zero_inst_match
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ROB_full
add wave -noupdate -expand /cpu_tb_rf/CPU_top/control_unit_top/LAB/LAB
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_data_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/RF_in_demux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/RF_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out_1_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF_out_1
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out_2_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF_out_2
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out_3_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF_out_3
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out3_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF_out_3_valid
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out_4_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF_out_4
add wave -noupdate /cpu_tb_rf/CPU_top/ID_RF_out4_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF_out_4_valid
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_valid
add wave -noupdate -expand /cpu_tb_rf/CPU_top/RF/RF
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_revalidate
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/clear_ID_IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/clear_EX_IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/clear_MEM_IW_out
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out2_reg
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_in_1
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_in_2
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/non_specul_out
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_top_mux_out
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_out_top
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/store_inst
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/load_inst
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/wren_non_speculative
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/st_buff
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/instruction_word
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_top_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_top_mux_out
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_top
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/MEM_out_top_reg
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/buffer_st_in
add wave -noupdate /cpu_tb_rf/CPU_top/WB_data
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_RF_in_demux
add wave -noupdate /cpu_tb_rf/CPU_top/WB_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/WB_RF_in_demux
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/RF_in_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/RF_in_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_op
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_inst_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_d1_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_d2_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_immediate_val
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_fwd_data_out_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_mem_addr_out
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_MEM_out_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_MEM_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_top_out_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU_top_out_2
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_slave_addr
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_GPIO_in_en
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_GPIO_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_I2C_r_en
add wave -noupdate /cpu_tb_rf/CPU_top/MEM_I2C_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/I2C_error
add wave -noupdate /cpu_tb_rf/CPU_top/I2C_op_run
add wave -noupdate /cpu_tb_rf/CPU_top/GPIO_out
add wave -noupdate /cpu_tb_rf/CPU_top/I2C_out
add wave -noupdate /cpu_tb_rf/CPU_top/n_sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/I2C_error_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/PC_CU_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/RF_in_3
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/PM_data_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/RF_in_4
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/RF_in_3_valid
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/RF_in_4_valid
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_SR_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/I2C_error
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/I2C_op_run
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out_1_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out_2_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out_3_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out_4_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out3_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_RF_out4_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_d1_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_d2_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_fwd_data_out_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_op
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_inst_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_mem_addr_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ALU_immediate_val
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_MEM_out_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_MEM_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_GPIO_in_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_GPIO_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_I2C_r_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_I2C_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_slave_addr
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_out_top
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/GPIO_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/I2C_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_data_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_stall
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_ID_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_mem_addr_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_ID_fwd_reg1
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB_ID_fwd_reg2
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_EX_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_EX_mem_address
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_EX_immediate_val
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_EX_fwd_reg1
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_EX_fwd_reg2
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_MEM_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_WB_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ROB_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/stall_pipeline
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ID_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/EX_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/MEM_IW
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ID_reset
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/EX_reset
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/MEM_reset
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/PM_data_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_in_3
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_in_4
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_in_3_valid
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_in_4_valid
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ROB_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ALU_SR_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/MEM
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/LAB_reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/LAB_stall
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_out_3_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_out_4_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_out_3_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/RF_out_4_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/PC_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/LAB_full
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/MEM_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/IW_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ld_st
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ld_st_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/reg2_used
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/IW_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/ID_stall_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/mem_addr_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/ALU_fwd_reg_1_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/ALU_fwd_reg_2_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/RF_out_1_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/RF_out_2_mux
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/RF_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/RF_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/immediate_val
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/mem_addr_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/ALU_fwd_reg_1_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/ALU_fwd_reg_2_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/RF_out_1_mux_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/RF_out_2_mux_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/mem_addr_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/immediate_val_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/ID_actual/reset_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/IW_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/EX_stall_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/mem_addr_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/immediate_val_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_fwd_reg_1_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_fwd_reg_2_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_d1_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_d2_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_fwd_data_out_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_op
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_inst_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/EX_stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/mem_addr_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/immediate_val
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/reset_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_op_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/ALU_inst_sel_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/immediate_val_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/EX_actual/mem_addr_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/IW_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/MEM_stall_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/I2C_error
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/I2C_op_run
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/MEM_out_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/MEM_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/GPIO_in_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/GPIO_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/I2C_r_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/I2C_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/slave_addr
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/I2C_error_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/reset_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/reset_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/MEM_stall_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/ION_results_ready_reg
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/MEM_actual/I2C_machine
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/reset_MEM
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/IW_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/PM_data_in
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/MEM_out_top
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/GPIO_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/I2C_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/stall_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/ROB_out
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux_sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_data
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/i
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/j
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/next_IW_is_addr
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux/data2x
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux/data3x
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/WB_actual/WB_out_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/PM/address
add wave -noupdate /cpu_tb_rf/CPU_top/PM/clock
add wave -noupdate /cpu_tb_rf/CPU_top/PM/q
add wave -noupdate /cpu_tb_rf/CPU_top/RF/clk
add wave -noupdate /cpu_tb_rf/CPU_top/RF/WB_data_in
add wave -noupdate /cpu_tb_rf/CPU_top/RF/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/RF/wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_1_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_2_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_3_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_4_mux
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_1_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_2_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_3_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_4_en
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_in_demux
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_1
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_2
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_3
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_4
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_3_valid
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_out_4_valid
add wave -noupdate /cpu_tb_rf/CPU_top/RF/RF_valid
add wave -noupdate /cpu_tb_rf/CPU_top/RF/in_index
add wave -noupdate /cpu_tb_rf/CPU_top/RF/out1_index
add wave -noupdate /cpu_tb_rf/CPU_top/RF/out2_index
add wave -noupdate /cpu_tb_rf/CPU_top/RF/out3_index
add wave -noupdate /cpu_tb_rf/CPU_top/RF/out4_index
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/MEM_in
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/MEM_address
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/value_immediate
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ALU_fwd_reg_1
add wave -noupdate /cpu_tb_rf/CPU_top/control_unit_top/LAB/ALU_fwd_reg_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_op
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_d1_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_d2_in_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out1_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out2_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_fwd_data_out_en
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_top_out_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_top_out_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out1_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_out2_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_SR_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_data_in_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_data_in_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_status
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/carry_in
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/data_in_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/data_in_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_op
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_inst_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_status
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_c
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_v
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/sub_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/divide_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/divide_remainder
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/div_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_neg
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_zero
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/log_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_result_final
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_in
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rot_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_in_left
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_in_right
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_overflow
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/sftl_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_overflow
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/sfta_SR
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_LSB
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_MSB
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_inst/add_sub
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_inst/dataa
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_inst/datab
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_inst/cout
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_inst/overflow
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/add_sub_inst/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_inst/dataa
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_inst/datab
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/mult_inst/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/divider_inst/denom
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/divider_inst/numer
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/divider_inst/quotient
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/divider_inst/remain
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/A_in
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/B_in
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/logic_func
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/zero
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/negative
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/and_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/or_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/xor_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/not_result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/and_zero
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/or_zero
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/xor_zero
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/logic_unit_inst/not_zero
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_inst/data
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_inst/direction
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_inst/distance
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_inst/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_inst/data
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_inst/direction
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_inst/distance
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_inst/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_inst/data
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_inst/direction
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_inst/distance
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_inst/overflow
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_logic_inst/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_unit/data
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_unit/direction
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_unit/distance
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_unit/overflow
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/shift_arith_unit/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data2x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data3x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data4x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data5x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data6x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/data7x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_1_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data2x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data3x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data4x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data5x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data6x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/data7x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/ALU_out_2_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data2x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data3x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data4x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data5x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data6x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/data7x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/status_out_2_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_final/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_final/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_final/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_final/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_final/LPM_MUX_component/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_in_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_in_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_in_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_inst/rotate_c_in_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_1_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_1_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_1_mux/data2x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_1_mux/data3x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_1_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_1_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_2_mux/data0x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_2_mux/data1x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_2_mux/data2x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_2_mux/data3x
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_2_mux/sel
add wave -noupdate /cpu_tb_rf/CPU_top/ALU/ALU_in_2_mux/result
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/data_out
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/data_memory/address
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/data_memory/clock
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/data_memory/data
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/data_memory/wren
add wave -noupdate /cpu_tb_rf/CPU_top/MEM/data_memory/q
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/clk
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/digital_in
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/ION_data_in
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/slave_addr
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/GPIO_in_en
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/GPIO_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_r_en
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_wr_en
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/digital_out
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_error
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_op_run
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/GPIO_out
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_out
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_sda
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_scl
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/GPIO_out_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_out_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/output_buffer
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/scl_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/sda_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/data_from_slave
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/slave_address
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/r_wr_comp
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_op_complete
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/read_begin
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/write_begin
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_error_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/slave_ack_success
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_out_buffer
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_in_buffer
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_op_state
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/scl
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/sda
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/reset_n
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/write_begin
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/read_begin
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/slave_address
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/data_to_slave
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/read_error
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/data_from_slave
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/r_wr_complete
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/state_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/cmd_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/bits_processed_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/clk_divider
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/continue_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/sda_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/sda_debounced
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/addr_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/slave_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/data_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/data_from_slave_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/scl_o_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/sda_o_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/clk_reg
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/slave_read_retry
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/data_valid
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/scl_run
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/start_stop
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/scl_status
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/addr_sent
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/SDA_debounce/data_clock
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/SDA_debounce/sys_clock
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/SDA_debounce/debounced_clock
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/SDA_debounce/flipflops
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/SDA_debounce/counter_set
add wave -noupdate /cpu_tb_rf/CPU_top/ION_actual/I2C_master/SDA_debounce/counter_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {86352 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 383
configure wave -valuecolwidth 120
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {52245 ps} {140549 ps}
